FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY public ./public
COPY server ./server

# EasyPanel envia as variáveis como build-args; copiamos para o runtime.
ARG PORT=3000
ARG CERTIFICATE_API_URL=
ARG SEED_ALUNO_EMAIL=
ARG SEED_ALUNO_RGM=
ARG SEED_ALUNO_PASSWORD=
ARG SEED_ALUNO_NOME=
ARG DATABASE_HOST=
ARG DATABASE_PORT=
ARG DATABASE_NAME=
ARG DATABASE_USER=
ARG DATABASE_PASSWORD=
ARG DATABASE_SSL=false
ARG SUPABASE_URL=
ARG SUPABASE_KEY=
ARG SUPABASE_CURSOS_TABLE=cursos_catalogo_ia
ARG SUPABASE_CURSOS_COLUMN=curso

ENV NODE_ENV=production \
    PORT=$PORT \
    CERTIFICATE_API_URL=$CERTIFICATE_API_URL \
    SEED_ALUNO_EMAIL=$SEED_ALUNO_EMAIL \
    SEED_ALUNO_RGM=$SEED_ALUNO_RGM \
    SEED_ALUNO_PASSWORD=$SEED_ALUNO_PASSWORD \
    SEED_ALUNO_NOME=$SEED_ALUNO_NOME \
    DATABASE_HOST=$DATABASE_HOST \
    DATABASE_PORT=$DATABASE_PORT \
    DATABASE_NAME=$DATABASE_NAME \
    DATABASE_USER=$DATABASE_USER \
    DATABASE_PASSWORD=$DATABASE_PASSWORD \
    DATABASE_SSL=$DATABASE_SSL \
    SUPABASE_URL=$SUPABASE_URL \
    SUPABASE_KEY=$SUPABASE_KEY \
    SUPABASE_CURSOS_TABLE=$SUPABASE_CURSOS_TABLE \
    SUPABASE_CURSOS_COLUMN=$SUPABASE_CURSOS_COLUMN

EXPOSE 3000

CMD ["node", "server/index.js"]
